/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PatternImport } from './routes/pattern'
import { Route as MainImport } from './routes/main'
import { Route as ArrayImport } from './routes/array'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PatternRoute = PatternImport.update({
  id: '/pattern',
  path: '/pattern',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const ArrayRoute = ArrayImport.update({
  id: '/array',
  path: '/array',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/array': {
      id: '/array'
      path: '/array'
      fullPath: '/array'
      preLoaderRoute: typeof ArrayImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/pattern': {
      id: '/pattern'
      path: '/pattern'
      fullPath: '/pattern'
      preLoaderRoute: typeof PatternImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/main': typeof MainRoute
  '/pattern': typeof PatternRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/main': typeof MainRoute
  '/pattern': typeof PatternRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/main': typeof MainRoute
  '/pattern': typeof PatternRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/array' | '/main' | '/pattern'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/array' | '/main' | '/pattern'
  id: '__root__' | '/' | '/array' | '/main' | '/pattern'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrayRoute: typeof ArrayRoute
  MainRoute: typeof MainRoute
  PatternRoute: typeof PatternRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrayRoute: ArrayRoute,
  MainRoute: MainRoute,
  PatternRoute: PatternRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/array",
        "/main",
        "/pattern"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/array": {
      "filePath": "array.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/pattern": {
      "filePath": "pattern.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
